#pragma once

#include "Base/BaseTypes.h"

enum CommandID : DAVA::uint32
{
    CMDID_BATCH,
    CMDID_TRANSFORM,

    CMDID_ENTITY_ADD,
    CMDID_ENTITY_REMOVE,
    CMDID_ENTITY_CHANGE_PARENT,
    CMDID_ENTITY_LOCK,
    CMDID_PARTICLE_EMITTER_MOVE,
    CMDID_PARTICLE_LAYER_REMOVE,
    CMDID_PARTICLE_LAYER_MOVE,
    CMDID_PARTICLE_FORCE_REMOVE,
    CMDID_PARTICLE_SIMPLIFIED_FORCE_MOVE,
    CMDID_PARTICLE_FORCE_MOVE,
    CMDID_GROUP_ENTITIES_FOR_MULTISELECT,
    CMDID_BAKE_GEOMERTY,

    CMDID_META_OBJ_MODIFY,
    CMDID_INSP_MEMBER_MODIFY,
    CMDID_INSP_DYNAMIC_MODIFY,
    CMDID_REFLECTED_FIELD_MODIFY,

    CMDID_KEYEDARCHIVE_ADD_KEY,
    CMDID_KEYEDARCHIVE_REM_KEY,
    CMDID_KEYEDARCHIVE_SET_KEY,

    CMDID_CUSTOM_COLORS_ENABLE,
    CMDID_CUSTOM_COLORS_DISABLE,
    CMDID_CUSTOM_COLORS_MODIFY,
    CMDID_VISIBILITY_TOOL_ENABLE,
    CMDID_VISIBILITY_TOOL_SET_POINT,
    CMDID_VISIBILITY_TOOL_SET_AREA,
    CMDID_HEIGHTMAP_EDITOR_ENABLE,
    CMDID_HEIGHTMAP_MODIFY,
    CMDID_TILEMASK_EDITOR_ENABLE,
    CMDID_TILEMASK_MODIFY,
    CMDID_SET_TILE_COLOR,
    CMDID_RULER_TOOL_ENABLE,
    CMDID_NOT_PASSABLE_TERRAIN_ENABLE,
    CMDID_NOT_PASSABLE_TERRAIN_DISABLE,

    CMDID_PARTICLE_EFFECT_UPDATE,
    CMDID_PARTICLE_EMITTER_UPDATE,
    CMDID_PARTICLE_EMITTER_POSITION_UPDATE,
    CMDID_PARTICLE_LAYER_UPDATE,
    CMDID_PARTILCE_LAYER_UPDATE_TIME,
    CMDID_PARTICLE_LAYER_UPDATE_ENABLED,
    CMDID_PARTICLE_LAYER_UPDATE_LODS,
    CMDID_PARTICLE_LAYER_CHANGED_MATERIAL_VALUES,
    CMDID_PARTICLE_LAYER_CHANGED_FLOW_VALUES,
    CMDID_PARTICLE_LAYER_CHANGED_NOISE_VALUES,
    CMDID_PARTICLE_LAYER_CHANGED_FRES_TO_ALPHA_VALUES,
    CMDID_PARTICLE_LAYER_CHANGED_STRIPE_VALUES,
    CMDID_PARTICLE_LAYER_CHANGED_ALPHA_REMAP,
    CMDID_PARTICLE_LAYER_CHANGED_THREE_POINT_GRADIENT,
    CMDID_PARTICLE_SIMPLIFIED_FORCE_UPDATE,
    CMDID_PARTICLE_FORCE_UPDATE,

    CMDID_PARTICLE_EMITTER_ADD,

    CMDID_PARTICLE_EFFECT_START_STOP,
    CMDID_PARTICLE_EFFECT_RESTART,
    CMDID_PARTICLE_EFFECT_EMITTER_REMOVE,

    CMDID_PARTICLE_EMITTER_LAYER_ADD,
    CMDID_PARTICLE_EMITTER_LAYER_REMOVE,
    CMDID_PARTICLE_EMITTER_LAYER_CLONE,
    CMDID_PARTICLE_EMITTER_SIMPLIFIED_FORCE_ADD,
    CMDID_PARTICLE_EMITTER_SIMPLIFIED_FORCE_REMOVE,
    CMDID_PARTICLE_EMITTER_DRAG_ADD,
    CMDID_PARTICLE_EMITTER_VORTEX_ADD,
    CMDID_PARTICLE_EMITTER_GRAVITY_ADD,
    CMDID_PARTICLE_EMITTER_WIND_ADD,
    CMDID_PARTICLE_EMITTER_POINT_GRAVITY_ADD,
    CMDID_PARTICLE_EMITTER_PLANE_COLLISION_ADD,
    CMDID_PARTICLE_EMITTER_FORCE_REMOVE,
    CMDID_PARTICLE_EMITTER_FORCE_CLONE,

    CMDID_PARTICLE_EMITTER_LOAD_FROM_YAML,
    CMDID_PARTICLE_EMITTER_SAVE_TO_YAML,

    CMDID_PARTICLE_INNER_EMITTER_LOAD_FROM_YAML,
    CMDID_PARTICLE_INNER_EMITTER_SAVE_TO_YAML,
    CMDID_PARTICLE_RELOAD_EMITTERS,

    CMDID_CONVERT_TO_SHADOW,

    CMDID_LOD_DISTANCE_CHANGE,
    CMDID_LOD_CREATE_PLANE,
    CMDID_LOD_COPY_LAST_LOD, //TODO: remove after lod editing implementation
    CMDID_LOD_DELETE,

    CMDID_COMPONENT_ADD,
    CMDID_COMPONENT_REMOVE,

    CMDID_MATERIAL_SWITCH_PARENT,
    CMDID_MATERIAL_GLOBAL_SET,
    CMDID_MATERIAL_REMOVE_TEXTURE,
    CMDID_MATERIAL_REMOVE_CONFIG,
    CMDID_MATERIAL_CREATE_CONFIG,
    CMDID_MATERIAL_CHANGE_CURRENT_CONFIG,
    CMDID_MATERIAL_CHANGE_CONFIG_NAME,
    CMDID_MATERIAL_APPLY_PRESET,

    CMDID_REBUILD_TANGENT_SPACE,
    CMDID_DELETE_RENDER_BATCH,
    CMDID_IMAGE_REGION_COPY,

    CMDID_SOUND_ADD_EVENT,
    CMDID_SOUND_REMOVE_EVENT,
    CMDID_SOUND_SET_EVENT_FLAGS,

    CMDID_CLONE_LAST_BATCH,

    CMDID_ENABLE_WAYEDIT,
    CMDID_DISABLE_WAYEDIT,
    CMDID_ADD_WAYPOINT,
    CMDID_REMOVE_WAYPOINT,
    CMDID_ADD_EDGE,
    CMDID_REMOVE_EDGE,

    CMDID_CONVERT_TO_BILLBOARD,

    CMDID_ATTACH_TO_SLOT,
    CMDID_EDIT_SLOT_FILTERS,

    CMDID_USER = 0xFFFF
};
