#ifndef __COLLADAERRORCODES_H__
#define __COLLADAERRORCODES_H__

enum eColladaErrorCodes
{
    COLLADA_OK = 0,
    COLLADA_ERROR,
    COLLADA_ERROR_OF_ROOT_NODE
};



#endif // __COLLADAERRORCODES_H__
